// App

// Auth
export const SET_AUTHENTICATION_STATUS = 'SET_AUTHENTICATION_STATUS';
export const SET_ONBOARDING_STATUS = 'SET_ONBOARDING_STATUS';

// User
export const SET_USER = 'SET_USER';
export const SET_USER_WALLET = 'SET_USER_WALLET';
export const SET_REWARD_CLAIM_AVAILABILITY = 'SET_REWARD_CLAIM_AVAILABILITY';

// Interface
export const SET_PROFILE_HEADER_VISIBLE = 'SET_PROFILE_HEADER_VISIBLE';

// Art
export const SAVE_GENERATED_ART = 'SAVE_GENERATED_ART';
export const SAVE_GENERATED_ART_IDS = 'SAVE_GENERATED_ART_IDS';
