// App

// Auth
export const SET_AUTHENTICATION_STATUS = 'SET_AUTHENTICATION_STATUS';
export const SET_ONBOARDING_STATUS = 'SET_ONBOARDING_STATUS';

// User
export const SET_USER = 'SET_USER';

// Interface
export const SET_PROFILE_HEADER_VISIBLE = 'SET_PROFILE_HEADER_VISIBLE';